### ISSUE TITLE
Bug: Blocked by CORS policy on local development

### ISSUE THREAD

**Issue by madatbay** [saleor/saleor#12504]
### What are you trying to achieve?

I want to set API and Dashboard locally, so I can deal with data through Dashboard 

### Steps to reproduce the problem

1. Run API with docker compose
2. Change env file in Dashboard folder `API_URI=http://localhost:8000/graphql/`
3. Run Dashboard
4. See Network Error

### What did you expect to happen?

Connect dashboard to API

### Logs

```
Access to XMLHttpRequest at 'http://localhost:8000/graphql/' from origin 'http://localhost:9000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

<img width="1680" alt="Screenshot 2023-04-06 at 15 59 41" src="https://user-images.githubusercontent.com/46858323/230372919-0171a780-0b12-4b2a-89a0-50926a37eb2f.png">

### Environment

Saleor version: API "3.13.0-a", Dashboard  "3.13.0-dev"
OS and version: macOS, 13.3, 22E252

**Comment by madatbay** [comment]
> Hi Madatbay! I saw your issue on the Saleor GitHub repo regarding connecting the dashboard to the API, and _I believe I can help you solve it_.
> 
> Based on the error message you shared, it looks like you are experiencing a **CORS** (Cross-Origin Resource Sharing) issue. To fix this issue, we can configure your Django API to allow cross-origin requests from the domain where your dashboard is hosted.
> 
> One way to do this is by using the **Django-cors-headers** package, which is a popular middleware for Django projects. I can guide you through the steps to install and configure this package.
> 
> Allow me to contribute or **assign me the task**

Thank you for your response. But if we consider docs, CORS issue should be solved with the help of `ALLOWED_CLIENT_HOSTS = defaults to localhost,127.0.0.1` and `ALLOWED_GRAPHQL_ORIGINS = default to *`. No 3rd party package is required

Even for testing purposes, i installed **django-cors-headers** and tested with it, yet result didn't change.

**Comment by ShubhChaturvedi** [comment]
> > Hi Madatbay! I saw your issue on the Saleor GitHub repo regarding connecting the dashboard to the API, and _I believe I can help you solve it_.
> > Based on the error message you shared, it looks like you are experiencing a **CORS** (Cross-Origin Resource Sharing) issue. To fix this issue, we can configure your Django API to allow cross-origin requests from the domain where your dashboard is hosted.
> > One way to do this is by using the **Django-cors-headers** package, which is a popular middleware for Django projects. I can guide you through the steps to install and configure this package.
> > Allow me to contribute or **assign me the task**
> 
> Thank you for your response. But if we consider docs, CORS issue should be solved with the help of `ALLOWED_CLIENT_HOSTS = defaults to localhost,127.0.0.1` and `ALLOWED_GRAPHQL_ORIGINS = default to *`. No 3rd party package is required
> 
> Even for testing purposes, i installed **django-cors-headers** and tested with it, yet result didn't change.

You're right that the Saleor documentation does mention **ALLOWED_CLIENT_HOSTS** and **ALLOWED_GRAPHQL_ORIGINS** settings as a way to configure CORS. However, it seems that in your case, it didn't solve the issue.

In such cases, it's possible that the preflight request, which is an HTTP OPTIONS request, is not being handled properly by the Django app. This can lead to CORS-related errors such as the one you're seeing. The **django-cors-headers** package provides a middleware that can handle the preflight request automatically and add the necessary CORS headers to the response.

**Comment by madatbay** [comment]
@ShubhChaturvedi Unfortunately, I have tried that 3rd party package multiple times but didn't solve my issue.

**Comment by madatbay** [comment]
Default settings using **django-cors-headers** are not enough. After all, it raises different preflight errors the "auhtorization-bearer" header is missing, and the cors credential error. For a complete solution it required to add:

```
from corsheaders.defaults import default_headers

CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",
        "http://localhost:9000",
    ]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = list(default_headers) + [
        "authorization-bearer",
    ]
```

**Comment by fedexin40** [comment]
@madatbay thanks for your answer, this issue was getting me crazy :100:

**Comment by AnthonyDreams** [comment]
Do we really need to install third-party packages to solve this?

**Comment by madatbay** [comment]
As per Saleor's documentation, we shouldn't. But it's how it's. I didn't find a way to solve this issue without 3rd party package.

But I agree with you, and this issue must be solved internally. Reopening the issue.

**Comment by varada13** [comment]
which 3rd party package u guys talking about, in saleor docs i cant find anything related to cors

**Comment by vimm0** [comment]
Hi @varada13,

For local development one could install [django-cors-headers](https://pypi.org/project/django-cors-headers/) and add below code to `settings.py`
```
from corsheaders.defaults import default_headers
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_HEADERS = list(default_headers) + [
        "authorization-bearer",
    ]
```

But `CORS_ALLOW_ALL_ORIGINS` **can be dangerous for production so use wisely**  as their documentation says,

> Setting this to True can be dangerous, as it allows any website to make cross-origin requests to yours. Generally you’ll want to restrict the list of allowed origins with CORS_ALLOWED_ORIGINS or CORS_ALLOWED_ORIGIN_REGEXES.

**Comment by maarcingebala** [comment]
Saleor doesn't need `django-cors-headers`; we have the `cors_handler` function implemented in the repo, but it's an async one. Django's default `runserver` won't handle it for local development. You can run it using:
```
python -m saleor
```

or

```
uvicorn saleor.asgi:application --reload

```

I think it's missing in the docs - we will fix it. See https://github.com/saleor/saleor/pull/11415.

**Comment by patrys** [comment]
Folks, you definitely don't need to install any third-party libraries. For local development, make sure you're starting Saleor using `uvicorn saleor.asgi:application --reload` and not using `python manage.py runserver` as Saleor requires ASGI to function. If it still does not work, please provide more details on how to reproduce your problem.

**Comment by JPaulMora** [comment]
Could I suggest adding this to the documentation? perhaps set it as default instead of the current sleep loop? https://github.com/saleor/saleor/blob/3402a722b67285052789d64610324be1639d203e/.devcontainer/docker-compose.yml#L9

Alternatively, if runserver is completely broken/not used by saleor a more robust solution could be to [override it](https://stackoverflow.com/a/18594835/5568813) to print a message and exit?

**Comment by patrys** [comment]
@JPaulMora devcontainers are not supposed to start any services. It's impossible to restart them, and if the default command crashes, the entire container disappears. The main command being `sleep` is the industry standard.

**Comment by JPaulMora** [comment]
@patrys thanks, you're right. What about the other suggestion?
